services:
  - type: web
    name: reserva-ingressos
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: STORAGE_BACKEND
        value: firebase
      - key: SECRET_KEY
        generateValue: true
      - key: PANEL_USERNAME
        value: operador5979
      - key: PANEL_PASSWORD
        value: reservas10
      - key: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
        sync: false
      - key: ZOHO_SMTP_HOST
        value: smtp.zoho.com
      - key: ZOHO_SMTP_PORT
        value: 465
      - key: ZOHO_SMTP_USERNAME
        sync: false
      - key: ZOHO_SMTP_PASSWORD
        sync: false
      - key: ZOHO_SMTP_FROM_EMAIL
        sync: false
      - key: ZOHO_SMTP_FROM_NAME
        value: Clube Rincão
      - key: ZOHO_SMTP_USE_SSL
        value: true
